version: "3.8"

services:
  bot:
    build: .
    container_name: alexbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/app/data
      - ./alexbot.db:/app/alexbot.db
